### PR TITLE
Bzz stub hello world protocol

### PR DESCRIPTION
**Pull request by nolash**
A crude shim to transmit handshake to a golang swarm peer. If run against a peer built on c535b271536d0dee5bd97c2541ca32a42f272d4f (ethersphere/swarm) the peer address should appear in the peer's kademlia.

### CODE REVIEW

**Comment by oskarth** [comment]
Sorry I didn't see the notification for this one, nice!

**Comment by oskarth** [comment]
@kdeme fyi, it'd be cool if we could get this to nim-eth repo upstream

**Comment by kdeme** [comment]
Cool! I had in my mind to look into reusing the whisper primitives for trying out some quick bzz, but didn't have the time to look into it so far. I'll definitely check this out soon!

**Comment by kdeme** [comment]
As you can see, I've created PR https://github.com/status-im/nim-eth/pull/100 on nim-eth to add the important parts of this PR.

**Pull request merged**
